// Command dwarfgen extracts sandboxapi request/response structs from an unstripped
// sbx binary's DWARF and emits Go definitions into internal/api/types_gen.go.
// Usage: go run ./internal/tools/dwarfgen -bin /usr/bin/sbx -out internal/api/types_gen.go
//
// DWARF carries field names/types/optionality but NOT struct tags, so json tags are
// derived as snake_case(FieldName) (+omitempty for pointer fields) and validated by
// internal/api/types_validate_test.go against live daemon JSON.
package main

import (
	"bytes"
	"debug/dwarf"
	"debug/elf"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

// roots is the curated set of sandboxapi types to extract (closure followed automatically).
var roots = []string{
	"github.com/docker/sandboxes/sandboxapi.SandboxInfo",
	"github.com/docker/sandboxes/sandboxapi.WorkspaceMount",
	"github.com/docker/sandboxes/sandboxapi.PublishedPort",
	"github.com/docker/sandboxes/sandboxapi.SandboxWorktree",
	"github.com/docker/sandboxes/sandboxapi.HealthResponse",
	"github.com/docker/sandboxes/sandboxapi.DaemonInfo",
}

func main() {
	bin := flag.String("bin", "/usr/bin/sbx", "path to unstripped sbx binary")
	out := flag.String("out", "internal/api/types_gen.go", "output file")
	flag.Parse()

	f, err := elf.Open(*bin)
	must(err)
	defer f.Close()
	d, err := f.DWARF()
	must(err)

	emitted := map[string]bool{}
	queue := append([]string{}, roots...)
	var b bytes.Buffer
	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		if emitted[name] {
			continue
		}
		st := findStruct(d, name)
		if st == nil {
			fmt.Fprintf(os.Stderr, "warning: type not found in DWARF: %s\n", name)
			emitted[name] = true
			continue
		}
		emitStruct(&b, name, st, &queue)
		emitted[name] = true
	}

	src := "// Code generated by dwarfgen from sbx " + *bin + "; DO NOT EDIT.\n\n" +
		"package api\n\nimport \"time\"\n\nvar _ = time.Time{}\n\n" + b.String()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		formatted = []byte(src) // emit unformatted on error so it can be inspected
	}
	must(os.WriteFile(*out, formatted, 0o644))
	fmt.Printf("wrote %s (%d types)\n", *out, len(emitted))
}

func findStruct(d *dwarf.Data, fqName string) *dwarf.StructType {
	r := d.Reader()
	for {
		e, err := r.Next()
		if err != nil || e == nil {
			return nil
		}
		if e.Tag != dwarf.TagStructType {
			continue
		}
		if n, _ := e.Val(dwarf.AttrName).(string); n == fqName {
			typ, err := d.Type(e.Offset)
			if err != nil {
				return nil
			}
			if st, ok := typ.(*dwarf.StructType); ok {
				return st
			}
		}
	}
}

func emitStruct(b *bytes.Buffer, fqName string, st *dwarf.StructType, queue *[]string) {
	fmt.Fprintf(b, "// %s\ntype %s struct {\n", short(fqName), goTypeName(short(fqName)))
	type fld struct{ name, gotype, tag string }
	var fields []fld
	for _, m := range st.Field {
		if m.Name == "" || !exported(m.Name) {
			continue
		}
		gt, dep := mapType(m.Type.String())
		if dep != "" {
			*queue = append(*queue, dep)
		}
		jsonName := snake(m.Name)
		tag := jsonName
		if strings.HasPrefix(gt, "*") || strings.HasPrefix(gt, "[]") {
			tag += ",omitempty"
		}
		fields = append(fields, fld{m.Name, gt, tag})
	}
	sort.SliceStable(fields, func(i, j int) bool { return fields[i].name < fields[j].name })
	for _, fl := range fields {
		fmt.Fprintf(b, "\t%s %s `json:\"%s\"`\n", fl.name, fl.gotype, fl.tag)
	}
	fmt.Fprint(b, "}\n\n")
}

// mapType converts a DWARF type string to a Go type and, if it references another
// sandboxapi type, returns that type's fully-qualified name to enqueue.
func mapType(s string) (gotype, dep string) {
	s = strings.TrimPrefix(s, "struct ")
	switch {
	case s == "string" || s == "bool" || s == "int" || s == "int64" || s == "uint32" || s == "float64":
		return s, ""
	case s == "*time.Time" || s == "time.Time":
		return s, ""
	case strings.HasPrefix(s, "*"):
		inner, dep := mapType(strings.TrimPrefix(s, "*"))
		return "*" + inner, dep
	case strings.HasPrefix(s, "[]"):
		inner, dep := mapType(strings.TrimPrefix(s, "[]"))
		return "[]" + inner, dep
	case strings.Contains(s, "sandboxapi."):
		return goTypeName(short(s)), s
	default:
		return "string", "" // fallback: enum/defined string types serialize as strings
	}
}

func short(fq string) string {
	if i := strings.LastIndex(fq, "."); i >= 0 {
		return fq[i+1:]
	}
	return fq
}
func goTypeName(s string) string { return s }
func exported(name string) bool  { return name != "" && name[0] >= 'A' && name[0] <= 'Z' }

func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r + 32)
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
