// Code generated by dwarfgen from sbx /usr/bin/sbx; DO NOT EDIT.
//
// Post-generation reconciliation (manual): the sandboxapi enum types
// SandboxStatus and PublishedPort.Protocol are defined string types
// (`type X string`) that carry no struct fields in DWARF, so dwarfgen emitted
// them as empty structs. The daemon serializes them as JSON strings
// (e.g. "running", "tcp"), so SandboxInfo.Status and
// PublishedPort.Protocol are typed `string` here and the empty enum structs
// were removed.
//
// Likewise SandboxInfo.Labels: DWARF reports it as a string, but the daemon
// serializes it as a JSON object (map of label key -> value), so it is typed
// `*map[string]string` here.
//
// SandboxInfo.CredentialSources: DWARF reports it as
// `map[string]CredentialSourceInfo`, but dwarfgen has no map case so it
// collapses the value type and emits `*CredentialSourceInfo`; it is widened
// back to `*map[string]CredentialSourceInfo` here (keyed by service name).
//
// Re-running dwarfgen will reintroduce the empty structs, re-widen Labels to
// *string, and re-collapse CredentialSources; re-apply these edits if you
// regenerate.

package api

import "time"

var _ = time.Time{}

// SandboxInfo
type SandboxInfo struct {
	AdditionalWorkspaces *[]WorkspaceMount                `json:"additional_workspaces,omitempty"`
	Agent                *string                          `json:"agent,omitempty"`
	CreatedAt            *time.Time                       `json:"created_at,omitempty"`
	CredentialSources    *map[string]CredentialSourceInfo `json:"credential_sources,omitempty"`
	Id                   string                           `json:"id"`
	Labels               *map[string]string               `json:"labels,omitempty"`
	MountPolicyDenied    *bool                            `json:"mount_policy_denied,omitempty"`
	Name                 string                           `json:"name"`
	Ports                *[]PublishedPort                 `json:"ports,omitempty"`
	Profile              *string                          `json:"profile,omitempty"`
	SourceRepoDir        *string                          `json:"source_repo_dir,omitempty"`
	Status               string                           `json:"status"`
	Workspace            string                           `json:"workspace"`
	Worktree             *SandboxWorktree                 `json:"worktree,omitempty"`
}

// WorkspaceMount
type WorkspaceMount struct {
	Dir      string `json:"dir"`
	ReadOnly *bool  `json:"read_only,omitempty"`
}

// PublishedPort
type PublishedPort struct {
	HostIp      string `json:"host_ip"`
	HostPort    int    `json:"host_port"`
	Protocol    string `json:"protocol"`
	SandboxPort int    `json:"sandbox_port"`
}

// SandboxWorktree
type SandboxWorktree struct {
	Branch            string `json:"branch"`
	OriginalWorkspace string `json:"original_workspace"`
}

// HealthResponse
type HealthResponse struct {
	ApiVersion *string          `json:"api_version,omitempty"`
	Release    bool             `json:"release"`
	Revision   *string          `json:"revision,omitempty"`
	Runtime    *RuntimeVersions `json:"runtime,omitempty"`
	Status     string           `json:"status"`
	Version    string           `json:"version"`
}

// DaemonInfo
type DaemonInfo struct {
	ApiSocket    string  `json:"api_socket"`
	DockerSocket *string `json:"docker_socket,omitempty"`
}

// CredentialSourceInfo
type CredentialSourceInfo struct {
	Source string `json:"source"`
	Type   string `json:"type"`
}

// RuntimeVersions
type RuntimeVersions struct {
	DockerNextCommit  *string `json:"docker_next_commit,omitempty"`
	DockerNextVersion *string `json:"docker_next_version,omitempty"`
	ShimVersion       *string `json:"shim_version,omitempty"`
	VmmCommit         *string `json:"vmm_commit,omitempty"`
}
